[package]
name = "ggez-specs-nphysics-hello-world"
version = "0.1.0"
authors = ["Rafael Delboni <rafadelboni@gmail.com>"]

[dependencies]
ggez = { version = "0.4", features = ["cargo-resource-root"] }
specs = "0.12"
nphysics2d = "0.9"
ncollide2d = "0.17.1"
hibitset = "0.5.1"
